### ISSUE TITLE
grep not matching fstab

### ISSUE THREAD

**Issue by lastsaskatchewanpirate** [Zackptg5/Disable_FEC_DmVerity#7]
Hi,

I tried using this to patch my Samsung SM-A320 (A3 2017).  This is running TWRP 3.2.3-0 (a3y17lte).

This version of TWRP isn't able to mount /data when it has quota enabled.  I added "quota" into the zip file name, but it still doesn't remove the quota entry from fstab.  On my device the relevant fstab file is fstab.samsungexynos7870 in the root of the ramdisk.

I have isolated the problem to the line 174 in boot_patch.sh:

> for i in $(cpio -t -F ramdisk.cpio | grep "fstab.\\|.fstab"); do

This grep command is not matching any of the three fstab.x files in the boot image (fstab.samsungexynos7870 / fstab.ranchu / fstab.goldfish).

If I change this to either of the following then everything works fine and the fstab is patched correctly

> for i in $(cpio -t -F ramdisk.cpio | grep -E "fstab.|.fstab"); do
or
> for i in $(cpio -t -F ramdisk.cpio | grep -e "fstab." -e ".fstab"); do

Is there any preference to which syntax to use, and could this cause any problems on other devices?

Thanks

Jack

**Comment by Zackptg5** [comment]
Hmm. Can you send a full recovery log with the original zip? I'm wondering if something's up with busybox cause I needed to escape it before. Either way, I'll probably change it to the second one since that one doesn't use any syntax that may vary with different greps

**Comment by lastsaskatchewanpirate** [comment]
This is the recovery log for the original zip (with "quota" added to the file name), applied to factory stock image with TWRP recovery

Hopefully this gives you the info you were looking for

[recovery.log](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3040994/recovery.log)

**Comment by lastsaskatchewanpirate** [comment]
For comparison, this is the recovery.log for the same setup (stock image plus TWRP) with modified zip to use 
> grep -e "fstab." -e ".fstab"
[recovery.log](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3041022/recovery.log)

**Comment by Zackptg5** [comment]
Odd. I'll change to the -e logic. Thanks!

**Comment by aIecxs** [comment]
According to man page, in basic regex (grep) the meta-character | lose his special meaning; instead using the backslashed version \\| is right.

In extended regex (grep -E) no need to escape the | character.

Both syntax are correct. It's not a busybox fault. android has its own grep binary, which seems not to understand escaped basic regex \\|

For better control we may use prefix busybox grep instead.

Btw in extended regex we need to escape \\. too because . is a wildcard for any character. we may also use option -i for case-insensitive search :)
